DROP TABLE DS_ROLE;
DROP TABLE DS_USER;
DROP TABLE DS_GROUP;
DROP TABLE DEPARTMENT;

DROP SEQUENCE SEQ_DS_USER;
DROP SEQUENCE SEQ_DS_GROUP;
DROP SEQUENCE SEQ_DS_ROLE;
DROP SEQUENCE SEQ_DEPARTMENT;

CREATE TABLE DS_USER (
  ID            NUMBER(11)    NOT NULL,
  FIRSTNAME     VARCHAR2(32)  NULL,
  LASTNAME      VARCHAR2(32)  NULL,
  AGE           NUMBER(3)     NULL,
  ACTIVE        NUMBER(1)     NULL,
  CREATED_AT    TIMESTAMP     NULL,
  EMAIL_ADDRESS VARCHAR2(128) NULL,
  MANAGER_ID    NUMBER(11)    NULL,
  BINARY_DATA   BLOB          NULL,
  DATE_OF_BIRTH DATE          NULL,
  country       VARCHAR2(64)  NULL,
  city          VARCHAR2(64)  NULL,
  street_name   VARCHAR2(64)  NULL,
  street_no     VARCHAR2(64)  NULL,
  PRIMARY KEY (ID)
);
CREATE SEQUENCE SEQ_DS_USER;
CREATE TABLE DS_ROLE (
  ID       NUMBER(11)   NOT NULL,
  NAME     VARCHAR2(32) NULL,
  GROUP_ID NUMBER(11)   NULL,
  PRIMARY KEY (ID)
);
CREATE SEQUENCE SEQ_DS_ROLE;

CREATE TABLE DS_GROUP (
  ID   NUMBER(11)   NOT NULL,
  NAME VARCHAR2(32) NULL,
  CODE VARCHAR2(32) NULL,
  PRIMARY KEY (ID)
);
CREATE SEQUENCE SEQ_DS_GROUP;

CREATE TABLE DEPARTMENT (
  ID                 NUMBER(11)   NOT NULL,
  NAME               VARCHAR2(32) NULL,
  version            NUMBER(11)   NULL,
  created_date       TIMESTAMP    NULL,
  last_modified_date TIMESTAMP    NULL,
  creator            NUMBER(11)   NULL,
  modifier           NUMBER(11)   NULL,
  PRIMARY KEY (ID)
);
CREATE SEQUENCE SEQ_DEPARTMENT;

CREATE TABLE ds_booking (
  ID            NUMBER(11)   NOT NULL,
  serial_number VARCHAR(32) NULL,
  amount        NUMBER(11)     NULL,
  user_id       NUMBER(11)     NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE SEQ_ds_booking;
